### ISSUE TITLE
where is the data which we have to use?

### ISSUE THREAD

**Issue by Himani-mogra1997** [beytullahsarica/MS-Lesion-Segmentation#1]
Or we will have to generate it ourselves? if yes, then how?

**Comment by beytullahsarica** [comment]
Yes, you have to generate the data yourself. You have to download datasets from their website and generate the npy files as explained in the paper. The download link is also available in the paper. Please read the paper for details.

**Comment by Himani-mogra1997** [comment]
Is it possible for you to provide the generated data?
